# Can override the default connection name with an environment variable as follows
#export SNOWFLAKE_DEFAULT_CONNECTION_NAME="default"

[default]
account = "ahunczr-dj57326"
user = "vamshi88"
password = "Dhanvik#99"
#role = "ACCOUNTADMIN"
role = "HOL_ROLE"
#warehouse = "COMPUTE_WH"
warehouse = "HOL_WH"
#database = "TESTDB"
database = "HOL_DB"
#schema = "PUBLIC"
